eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.197:8761/eureka/

server:
  port: 8765

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: eshop-datasync-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.0.104:3306/eshop?characterEncoding=utf-8
    username: root
    password: root
  rabbitmq:
    host: 192.168.0.104
    port: 5672
    username: guest
    password: guest